//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Test
	/// Data Source    : (localdb)\mssqllocaldb
	/// Server Version : 13.00.4001
	/// </summary>
	public partial class TestDB : LinqToDB.Data.DataConnection
	{
		public ITable<EFMigrationsHistory> EFMigrationsHistories { get { return this.GetTable<EFMigrationsHistory>(); } }
		public ITable<User>                Users                 { get { return this.GetTable<User>(); } }

		public TestDB()
			: base(providerName: "System.Data.SqlClient", connectionString: @"workstation id=TestDB14.mssql.somee.com;packet size=4096;user id=EllectroBit_SQLLogin_1;pwd=ugr6azqzqy;data source=TestDB14.mssql.somee.com;persist security info=False;initial catalog=TestDB14")
		{
			InitDataContext();
			InitMappingSchema();
		}

		public TestDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="__EFMigrationsHistory")]
	public partial class EFMigrationsHistory
	{
		[PrimaryKey, NotNull] public string MigrationId    { get; set; } // nvarchar(150)
		[Column,     NotNull] public string ProductVersion { get; set; } // nvarchar(32)
	}

	[Table(Schema="dbo", Name="Users")]
	public partial class User
	{
		[PrimaryKey, Identity] public int    Id   { get; set; } // int
		[Column,     NotNull ] public string Name { get; set; } // nvarchar(max)
		[Column,     NotNull ] public int    Age  { get; set; } // int
	}

	public static partial class TableExtensions
	{
		public static EFMigrationsHistory Find(this ITable<EFMigrationsHistory> table, string MigrationId)
		{
			return table.FirstOrDefault(t =>
				t.MigrationId == MigrationId);
		}

		public static User Find(this ITable<User> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
